# Generated by Django 3.0.2 on 2020-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='needs_updating',
            field=models.BooleanField(default=False),
        ),
    ]
