# Generated by Django 3.0.2 on 2020-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_needs_updating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
