# Generated by Django 3.0.2 on 2020-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_update_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
