# Generated by Django 3.0.3 on 2020-02-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200215_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='full_name',
            field=models.CharField(max_length=30, verbose_name='Your Name'),
        ),
    ]
