# Generated by Django 3.0.3 on 2020-02-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/%Y/%m/%d', verbose_name='Icon'),
        ),
    ]
