# Generated by Django 3.0.3 on 2020-02-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250, unique=True, verbose_name='Message')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
            ],
        ),
    ]
